### ISSUE TITLE
Fails to build with `default-features = false`

### ISSUE THREAD

**Issue by Shnatsel** [phylum-dev/purl#10]
# Overview
When added as a dependency in another project with `default-features = false`, or when running `cargo build --no-default-features`, the crate fails to build:

```
error[E0432]: unresolved import `smartstring`
  --> /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/purl-0.1.1/src/lib.rs:12:5
   |
12 | use smartstring::{LazyCompact, SmartString, SmartStringMode};
   |     ^^^^^^^^^^^ use of undeclared crate or module `smartstring`

For more information about this error, try `rustc --explain E0432`.
```

# How To Reproduce
Steps to reproduce this behavior:
1. `cargo build --no-default-features`

# Expected Behavior
No compilation failures

**Comment by kylewillmon** [comment]
Weird. We've got a [test for this][1] which isn't failing...

[1]: https://github.com/phylum-dev/purl/blob/4d17bd88ed4156a2e17c8d8214c358be55f12863/.github/workflows/main.yml#L51-L53

And indeed, `cargo build --no-default-features` succeeds at the workspace level. But `cargo build --no-default-features -p purl` fails.

Thanks for pointing this out. I'll get a PR up shortly to fix

**Comment by Shnatsel** [comment]
Thanks for the quick fix!

**Comment by maxrake** [comment]
@matt-phylum @kylewillmon
Does this repo still need another tag and release to crates.io?

**Comment by Shnatsel** [comment]
Getting a crates.io release with the fix soon would be very nice.

**Comment by maxrake** [comment]
v0.1.2, with these changes, is up on crates.io now. Thanks, @matt-phylum!
